version: '2'

services:

  app:
    image: tianon/true
    volumes:
      - ${APPLICATION}:/go/src

  workspace:
    build:
      context: ./golang
      args:
        - APP_DIR=${APP_DIR}
        - PORT=${GO_PORT}
    ports:
      - "${GO_PORT}:1323"
    volumes_from:
      - app
    tty: true
    networks:
      - backend

### RabbitMQ #############################################
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - workspace
    networks:
      - backend

networks:
  backend:
    driver: ${NETWORKS_DRIVER}